#!/bin/bash

echo "Setting up admin password system..."
echo "Please run the following SQL in your Supabase SQL Editor:"
echo ""
echo "1. Copy the contents of setup_admin_password.sql"
echo "2. Paste it into your Supabase SQL Editor"
echo "3. Execute the SQL"
echo ""
echo "Default admin credentials will be:"
echo "Email: admin@mizelconsulting.com"
echo "Password: admin123"
echo ""
echo "You can change these in the SQL file before running it."
echo ""
echo "After running the SQL, you can login at:"
echo "http://localhost:3001/login"
echo ""
echo "The admin dashboard will be available at:"
echo "http://localhost:3001/admin-dashboard"
